Fix for MSVC 14 (VS 2015) -- Compiler complains about functions like (std::ostream& NM_FOM_Dimension::show(std::ostream& out)) when they are the right-hand value for an << operator. It also seems superfluous to do this in all cases the ostream in which was "written" by show was the same as the parameter "out".
Error: binary '<<': no operator found which takes a left-hand operand of type 'std::ostream' (or there is no acceptable conversion)	LibCERTI	C:\Users\Joris Goosen\Documents\CERTI Enzo\CERTI-3_5_1\libCERTI\NM_Classes.cc	96	Build